Repository CS2103-AY1819S1-W12-3/main, pull requests merged in 2018-10, with the labels that each got.

#66 Add import command to developer guide
  docs/DeveloperGuide.adoc
  docs/images/AddMutipleCardsSequenceDiagram.png
  docs/images/ImportCommandActivityDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/StorageComponentClassDiagram.png
Labels: priority.High, status.ReadyForReview, type.Task

#67 Update DG on implementation of MatchTest
  docs/DeveloperGuide.adoc
  docs/images/MatchTestActivityDiagram.png
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StartingMatchTestSequenceDiagram.png
Labels: priority.High, type.Task

#68 updated user guide (non-technical)
  docs/UserGuide.adoc
Labels: priority.Medium, severity.Low

#73 added UI library
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: priority.High, status.ReadyForReview

#86 Remove AddressBook from UserGuide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/UsingCheckstyle.adoc
Labels: priority.Low, severity.Low, status.ReadyForReview

#93 Add import file parser
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/fileparser/FileParserUtil.java
  src/main/java/seedu/address/logic/parser/fileparser/exceptions/FileParseException.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TriviaBundle.java
  src/main/java/seedu/address/model/card/UniqueCardList.java
  src/main/java/seedu/address/model/portation/ImportFile.java
  src/main/java/seedu/address/ui/home/ImportHelpDisplay.java
  src/test/data/TxtFileUtilTest/typicalTest.txt
  src/test/data/TxtFileUtilTest/validTest.txt
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/FileUtil.java
  src/test/java/seedu/address/testutil/ImportFileUtil.java
Labels: status.ReadyForReview

#90 Improve UI for MatchTest
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/parser/MatchTestCommandParser.java
  src/main/java/seedu/address/model/card/IndexedAnswer.java
  src/main/java/seedu/address/model/card/IndexedQuestion.java
  src/main/java/seedu/address/model/test/TriviaResult.java
  src/main/java/seedu/address/model/test/TriviaTest.java
  src/main/java/seedu/address/model/test/matchtest/MatchAttempt.java
  src/main/java/seedu/address/model/test/matchtest/MatchTest.java
  src/main/java/seedu/address/ui/test/matchtest/AnswerListPanel.java
  src/main/java/seedu/address/ui/test/matchtest/AnswerView.java
  src/main/java/seedu/address/ui/test/matchtest/MatchAttemptView.java
  src/main/java/seedu/address/ui/test/matchtest/MatchTestPage.java
  src/main/java/seedu/address/ui/test/matchtest/MatchTestResultPage.java
  src/main/java/seedu/address/ui/test/matchtest/QuestionListPanel.java
  src/main/java/seedu/address/ui/test/matchtest/QuestionView.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/test/matchtest/AnswerView.fxml
  src/main/resources/view/test/matchtest/MatchTestPage.fxml
  src/main/resources/view/test/matchtest/MatchTestResultPage.fxml
  src/main/resources/view/test/matchtest/QuestionView.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/logic/commands/MatchCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MatchTestCommandParserTest.java
  src/test/java/seedu/address/model/test/matchtest/MatchAttemptTest.java
  src/test/java/seedu/address/model/test/matchtest/MatchTestTest.java
  src/test/java/seedu/address/testutil/MatchTestUtil.java
Labels: status.ReadyForReview

#95 Update MatchTest DG according to v1.2 review
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/MatchCommandSequenceDiagram.png
  docs/images/MatchTestActivityDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StartingMatchTestSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/MatchTestCommand.java
Labels: status.Ongoing

#99 Update MatchTest
  build.gradle
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/state/State.java
  src/main/java/seedu/address/model/test/matchtest/MatchTest.java
  src/main/java/seedu/address/model/test/matchtest/exceptions/AnswerNotFoundException.java
  src/main/java/seedu/address/model/test/matchtest/exceptions/QuestionNotFoundException.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/test/matchtest/MatchTestResultPage.fxml
  src/test/java/seedu/address/logic/commands/MatchCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/test/matchtest/MatchTestTest.java
Labels: status.ReadyForReview

#103 Updated user guide:
  docs/UserGuide.adoc
  docs/figures/ImportUserGuide.pptx
  docs/images/user_guide/import/import-file-format.png
Labels: status.ReadyForReview

#104 Update dev guide:
  docs/DeveloperGuide.adoc
  docs/images/AddMutipleCardsSequenceDiagram.png
  docs/images/ImportCommandActivityDiagram.png
  docs/images/ImportMultipleCardsSequenceDiagram.png
Labels: status.ReadyForReview

#101 Change list command to learn
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/LearnCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/LearnCommandParser.java
  src/main/java/seedu/address/model/card/TopicIsKeywordPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/LearnCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/AppSystemTest.java
Labels: status.ReadyForReview

#107 Refactor import
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/fileparser/FileParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/portation/ImportFile.java
Labels: status.ReadyForReview

#106 Customizing Commands for 3VIA
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/ExtraInformationDisplay.java
  src/main/java/seedu/address/commons/events/model/TriviaResultsChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/CardPanelSelectionChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/DisplayBrowserEventChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/DisplayCardInfoEvent.java
  src/main/java/seedu/address/commons/events/ui/DisplayGoogleSearchEvent.java
  src/main/java/seedu/address/commons/events/ui/DisplayImportHelpChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/DisplayImportHelpEvent.java
  src/main/java/seedu/address/commons/events/ui/ExtraInformationDisplayChangeEvent.java
  src/main/java/seedu/address/commons/events/ui/JumpToListRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/SetUpDisplayCardInfoEvent.java
  src/main/java/seedu/address/logic/commands/GoogleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GoogleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/card/Card.java
  src/main/java/seedu/address/model/portation/ImportFile.java
  src/main/java/seedu/address/model/test/Attempt.java
  src/main/java/seedu/address/model/test/TriviaResults.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedAttempt.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TipBox.java
  src/main/java/seedu/address/ui/home/BrowserPanel.java
  src/main/java/seedu/address/ui/home/CardExperience.java
  src/main/java/seedu/address/ui/home/CardInfoPanel.java
  src/main/java/seedu/address/ui/home/CardListPanel.java
  src/main/java/seedu/address/ui/home/CardMostRecentMistake.java
  src/main/java/seedu/address/ui/home/Homepage.java
  src/main/java/seedu/address/ui/home/ImportHelpDisplay.java
  src/main/java/seedu/address/ui/home/InfoPanel.java
  src/main/resources/images/cross_icon.png
  src/main/resources/images/lamp.png
  src/main/resources/images/tick_icon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TipBox.fxml
  src/main/resources/view/home/CardExperience.fxml
  src/main/resources/view/home/CardInfoPanel.fxml
  src/main/resources/view/home/CardMostRecentMistake.fxml
  src/main/resources/view/home/Homepage.fxml
  src/main/resources/view/home/InfoPanel.fxml
  src/test/data/XmlSerializableTriviaResultsTest/invalidResultTriviaResults.xml
  src/test/data/XmlSerializableTriviaResultsTest/typicalResultsTriviaResults.xml
  src/test/data/XmlTriviaResultsStorageTest/invalidAndValidResultTriviaResults.xml
  src/test/data/XmlTriviaResultsStorageTest/invalidResultTriviaResults.xml
  src/test/java/guitests/guihandles/CardInfoPanelHandle.java
  src/test/java/guitests/guihandles/InfoPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/storage/XmlAdaptedAttemptTest.java
  src/test/java/systemtests/AppSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: status.ReadyForReview

#108 Display imported card
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TriviaBundle.java
  src/main/java/seedu/address/model/card/Card.java
  src/main/java/seedu/address/model/card/UniqueCardList.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: status.ReadyForReview

#111 Updated import help display UI
  src/main/java/seedu/address/ui/home/ImportHelpDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/home/ImportHelpDisplay.fxml
Labels: status.ReadyForReview

#109 Update Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ModelClassDiagram.png
  docs/images/user_guide/match_test/match_command.png
Labels: status.Ongoing

#110 Update CardInfoPanel
  src/main/java/seedu/address/commons/events/ui/HideCardInfoPanelEvent.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/ui/home/CardMostRecentMistake.java
  src/main/java/seedu/address/ui/home/InfoPanel.java
  src/main/java/seedu/address/ui/test/matchtest/AnswerView.java
  src/main/java/seedu/address/ui/test/matchtest/MatchAttemptView.java
  src/main/java/seedu/address/ui/test/matchtest/MatchTestPage.java
  src/main/java/seedu/address/ui/test/matchtest/MatchTestResultPage.java
  src/main/java/seedu/address/ui/test/matchtest/QuestionView.java
  src/main/resources/view/home/CardMostRecentMistake.fxml
  src/main/resources/view/home/CardView.fxml
  src/main/resources/view/test/matchtest/AnswerView.fxml
  src/main/resources/view/test/matchtest/MatchAttemptView.fxml
  src/main/resources/view/test/matchtest/MatchTestPage.fxml
  src/main/resources/view/test/matchtest/QuestionView.fxml
Labels: status.Ongoing

#114 Update user guide - Import
  docs/UserGuide.adoc
  docs/figures/ImportUserGuide.pptx
  docs/images/import_file_format.png
  docs/images/import_step1.png
  docs/images/import_step2.png
  docs/images/user_guide/import/import-file-format.png
Labels: status.ReadyForReview

#112 Add support for clear command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TriviaBundle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
Labels: status.Ongoing

#113 Edits for v1.3
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/UserGuideMatchCommand.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/card/TopicIsKeywordPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/home/CardInfoPanel.java
  src/main/java/seedu/address/ui/home/CardMostRecentMistake.java
  src/main/resources/view/home/CardExperience.fxml
  src/main/resources/view/home/CardMostRecentMistake.fxml
  src/main/resources/view/test/matchtest/MatchTestPage.fxml
  src/test/java/seedu/address/model/card/TagIsKeywordPredicateTest.java
  src/test/java/systemtests/AppSystemTest.java
Labels: status.Ongoing
