Repository CS2103-AY1819S1-W12-3/main, pull requests merged in 2018-11, with the labels that each got.

#117 Edit EditCommand to prevent weird behaviour
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/ui/home/CardListPanel.java
  src/test/java/guitests/guihandles/CardInfoPanelHandle.java
  src/test/java/systemtests/AppSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: status.ReadyForReview

#118 Update dev guide
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/AlternativeImportClassDiagram.png
  docs/images/ImportMultipleCardsSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/StorageComponentClassDiagram.png
Labels: status.Ongoing

#119 Update MatchTest
  docs/UserGuide.adoc
  docs/images/UserGuideMatchCommand.png
  docs/images/UserGuideMatchCommandWithoutQuestion.png
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/parser/MatchCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/test/matchtest/MatchTest.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/java/seedu/address/ui/test/matchtest/AnswerListPanel.java
  src/main/java/seedu/address/ui/test/matchtest/AnswerView.java
  src/main/java/seedu/address/ui/test/matchtest/QuestionListPanel.java
  src/main/java/seedu/address/ui/test/matchtest/QuestionView.java
  src/test/java/seedu/address/logic/commands/MatchCommandTest.java
  src/test/java/seedu/address/logic/commands/MatchTestCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MatchCommandParserTest.java
  src/test/java/seedu/address/model/card/TopicIsKeywordPredicateTest.java
Labels: status.ReadyForReview

#120 Update UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/MatchTestActivityDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/ui/UiPart.java
  src/main/java/seedu/address/ui/test/matchtest/AnswerListPanel.java
  src/main/java/seedu/address/ui/test/matchtest/QuestionListPanel.java
Labels: status.ReadyForReview

#121 Add more sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: status.ReadyForReview

#148 Refactor MainWindow
  src/main/java/seedu/address/commons/events/ui/NavigateToLearnPageEvent.java
  src/main/java/seedu/address/logic/commands/LearnCommand.java
  src/main/java/seedu/address/ui/MainDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/java/seedu/address/ui/home/InfoPanel.java
  src/main/java/seedu/address/ui/test/TriviaTestMenuPage.java
  src/main/java/seedu/address/ui/test/TriviaTestPlaceholderPage.java
  src/main/resources/images/matchtest.png
  src/main/resources/view/MainDisplay.fxml
  src/main/resources/view/test/TriviaTestMenuPage.fxml
  src/main/resources/view/test/TriviaTestPlaceholderPage.fxml
Labels: status.ReadyForReview

#150 Add Project Portfolio Page [Jun Wei]
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ModelClassDiagram.png
  docs/team/junwei96.adoc
  docs/team/kohjunwei.adoc
Labels: status.ReadyForReview

#151 Add Project Portfolio Page [Zong Sien]
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/StorageClassDiagram.png
  docs/images/user_guide/import/import_file_format.png
  docs/images/user_guide/import/import_step1.png
  docs/team/hozongsien.adoc
Labels: status.Ongoing

#152 Update Misc Commands
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/card/Question.java
  src/main/java/seedu/address/ui/MainDisplay.java
  src/test/java/seedu/address/logic/parser/MatchCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: status.ReadyForReview

#153 Updated to provide detailed reasons for import failure
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/model/portation/ImportFile.java
  src/main/java/seedu/address/model/portation/exceptions/InvalidImportFileException.java
  src/test/java/seedu/address/model/portation/ImportFileTest.java
Labels: status.ReadyForReview

#123 Update test cases for MatchTest and CardInfoPanel
  docs/DeveloperGuide.adoc
  docs/team/junwei96.adoc
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/model/test/matchtest/MatchTest.java
  src/main/java/seedu/address/ui/home/CardExperience.java
  src/main/java/seedu/address/ui/home/CardInfoPanel.java
  src/main/java/seedu/address/ui/home/CardMostRecentMistake.java
  src/main/java/seedu/address/ui/test/matchtest/AnswerListPanel.java
  src/main/java/seedu/address/ui/test/matchtest/QuestionListPanel.java
  src/main/resources/view/test/matchtest/MatchAttemptView.fxml
  src/test/java/guitests/guihandles/CardExperienceHandle.java
  src/test/java/guitests/guihandles/CardInfoPanelHandle.java
  src/test/java/guitests/guihandles/CardListPanelHandle.java
  src/test/java/guitests/guihandles/CardMostRecentMistakeHandle.java
  src/test/java/guitests/guihandles/HomepageHandle.java
  src/test/java/guitests/guihandles/MainDisplayHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/triviatest/matchtest/AnswerListPanelHandle.java
  src/test/java/guitests/guihandles/triviatest/matchtest/AnswerViewHandle.java
  src/test/java/guitests/guihandles/triviatest/matchtest/MatchAttemptListHandle.java
  src/test/java/guitests/guihandles/triviatest/matchtest/MatchAttemptViewHandle.java
  src/test/java/guitests/guihandles/triviatest/matchtest/MatchTestPageHandle.java
  src/test/java/guitests/guihandles/triviatest/matchtest/MatchTestResultPageHandle.java
  src/test/java/guitests/guihandles/triviatest/matchtest/QuestionListPanelHandle.java
  src/test/java/guitests/guihandles/triviatest/matchtest/QuestionViewHandle.java
  src/test/java/seedu/address/logic/commands/MatchCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MatchCommandParserTest.java
  src/test/java/seedu/address/model/test/matchtest/MatchTestTest.java
  src/test/java/seedu/address/testutil/MatchIndexPair.java
  src/test/java/seedu/address/testutil/MatchTestUtil.java
  src/test/java/seedu/address/ui/CardInfoPanelTest.java
  src/test/java/seedu/address/ui/MatchTestPageTest.java
  src/test/java/seedu/address/ui/MatchTestResultPageTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: status.Ongoing

#160 Update MatchTest and CardInfoPanel according to new theme
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/CloseTriviaTestViewEvent.java
  src/main/java/seedu/address/commons/events/ui/NavigateToLearnPageEvent.java
  src/main/java/seedu/address/logic/commands/LearnCommand.java
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/commands/MatchTestCommand.java
  src/main/java/seedu/address/logic/commands/OpenEndedTestCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/state/AppState.java
  src/main/java/seedu/address/model/state/State.java
  src/main/java/seedu/address/model/test/matchtest/MatchTest.java
  src/main/java/seedu/address/ui/MainDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TipBox.java
  src/main/java/seedu/address/ui/test/TriviaTestPlaceholderPage.java
  src/main/java/seedu/address/ui/test/matchtest/MatchAttemptList.java
  src/main/java/seedu/address/ui/test/matchtest/MatchTestPage.java
  src/main/java/seedu/address/ui/test/matchtest/MatchTestResultPage.java
  src/main/resources/view/3VIATheme.css
  src/main/resources/view/MainDisplay.fxml
  src/main/resources/view/home/CardInfoPanel.fxml
  src/main/resources/view/test/TriviaTestMenuPage.fxml
  src/main/resources/view/test/matchtest/MatchTestPage.fxml
  src/main/resources/view/test/matchtest/MatchTestResultPage.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/MatchTestUtil.java
Labels: status.Ongoing

#161 UI Fixes
  src/main/java/seedu/address/ui/MainDisplay.java
  src/main/java/seedu/address/ui/home/CardMostRecentMistake.java
  src/main/resources/view/3VIATheme.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainDisplay.fxml
  src/main/resources/view/home/CardMostRecentMistake.fxml
  src/test/java/guitests/guihandles/CardMostRecentMistakeHandle.java
Labels: status.ReadyForReview

#162 Added more sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: status.ReadyForReview

#164 PPP-JunWei
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/MatchCommandSequenceDiagram.png
  docs/images/MatchTestActivityDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StartingMatchTestSequenceDiagram.png
  docs/team/junwei96.adoc
  src/main/java/seedu/address/commons/core/AsyncEventsCenter.java
  src/main/java/seedu/address/ui/UiPart.java
  src/test/java/seedu/address/ui/GuiUnitTest.java
  src/test/java/systemtests/AppSystemTest.java
Labels: status.ReadyForReview

#159 Update UI documentations
  README.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/TestPageDiagram.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/commons/events/ui/ChangeModeEvent.java
  src/main/java/seedu/address/logic/commands/LearnCommand.java
  src/main/java/seedu/address/logic/commands/ModeCommand.java
  src/main/java/seedu/address/logic/commands/NavigationCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/3VIADarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: status.ReadyForReview

#170 Refactored more code
  src/main/java/seedu/address/logic/parser/fileparser/FileParserUtil.java
  src/main/java/seedu/address/model/portation/ImportFile.java
  src/test/java/seedu/address/logic/parser/fileparser/FileParserUtilTest.java
Labels: status.Ongoing

#175 Update MatchTest
  src/main/resources/view/3VIATheme.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/test/matchtest/MatchTestPage.fxml
  src/main/resources/view/test/matchtest/MatchTestResultPage.fxml
Labels: status.ReadyForReview

#174 PPP - JunWei
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/MatchCommandSequenceDiagram.png
  docs/images/MatchTestActivityDiagram.png
  docs/images/UserGuideMatchCommand.png
  docs/images/UserGuideMatchCommandWithoutQuestion.png
  docs/stylesheets/asciidoctor.css
  docs/team/junwei96.adoc
Labels: status.ReadyForReview

#163 Bug Fixes with issue #158
  docs/team/chuajunhui.adoc
  docs/team/zihengxiu.adoc
  src/main/java/seedu/address/commons/events/model/TabChangeEvent.java
  src/main/java/seedu/address/commons/events/ui/ChangeModeEvent.java
  src/main/java/seedu/address/logic/commands/LearnCommand.java
  src/main/java/seedu/address/logic/commands/ReviewCommand.java
  src/main/java/seedu/address/logic/commands/TestCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/NavigationCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/3VIADarkTheme.css
  src/main/resources/view/3VIATheme.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightThemeExtensions.css
  src/main/resources/view/MainDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/test/TriviaTestMenuPage.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: priority.High

#169 PPP - Zong Sien
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/figures/ImportUserGuide.pptx
  docs/images/AlternativeImportClassDiagram.png
  docs/images/ImportCommandActivityDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/import_file_format.png
  docs/images/import_step1.png
  docs/images/import_step2.png
  docs/team/hozongsien.adoc
Labels: status.ReadyForReview
